-- +goose Up
-- Textbook vocabulary, units 1-4, as example sentences. *Asterisks* mark the word
-- being learned; the translation is for that word and the note holds its transcription.

SELECT add_word('en', 'we had a nice *chat* over coffee', 'дружеский разговор, болтовня', '/tʃæt/', ARRAY['unit-1']);
SELECT add_word('en', 'they plan to *construct* a new bridge', 'строить, сооружать', '/kənˈstrʌkt/', ARRAY['unit-1']);
SELECT add_word('en', 'the *construction* of the stadium took two years', 'строительство, конструкция', '/kənˈstrʌkʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'you can guess the meaning from the *context*', 'контекст', '/ˈkɒntɛkst/', ARRAY['unit-1']);
SELECT add_word('en', 'we had a long *conversation* about work', 'разговор, беседа', '/ˌkɒnvəˈseɪʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'let''s *discuss* it tomorrow', 'обсуждать', '/dɪˈskʌs/', ARRAY['unit-1']);
SELECT add_word('en', 'the *discussion* lasted an hour', 'обсуждение', '/dɪˈskʌʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'I need to *do revision* before the exam', 'повторять (материал)', '/duː rɪˈvɪʒən/', ARRAY['unit-1']);
SELECT add_word('en', 'don''t be afraid to *experiment* with new words', 'экспериментировать', '/ɪkˈspɛrɪmənt/', ARRAY['unit-1']);
SELECT add_word('en', 'can you *explain* this rule again?', 'объяснять', '/ɪkˈspleɪn/', ARRAY['unit-1']);
SELECT add_word('en', 'thanks for the clear *explanation*', 'объяснение', '/ˌɛkspləˈneɪʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'learning a *foreign* language takes time', 'иностранный', '/ˈfɒrɪn/', ARRAY['unit-1']);
SELECT add_word('en', 'as a *foreigner*, he found the city confusing', 'иностранец', '/ˈfɒrɪnə/', ARRAY['unit-1']);
SELECT add_word('en', 'this letter is too *formal* for a friend', 'официальный, формальный', '/ˈfɔːməl/', ARRAY['unit-1']);
SELECT add_word('en', 'I didn''t understand every word, but I got the *gist*', 'суть, главная идея', '/dʒɪst/', ARRAY['unit-1']);
SELECT add_word('en', 'let''s *go through* the text once more', 'просматривать, проходить', '/ɡəʊ θruː/', ARRAY['unit-1']);
SELECT add_word('en', 'try to *guess* the meaning of the word', 'догадаться, догадка', '/ɡɛs/', ARRAY['unit-1']);
SELECT add_word('en', 'let''s *have a chat* after the meeting', 'поболтать', '/hæv ə tʃæt/', ARRAY['unit-1']);
SELECT add_word('en', 'can you *identify* the main idea?', 'определить, распознать', '/aɪˈdɛntɪfaɪ/', ARRAY['unit-1']);
SELECT add_word('en', 'use *informal* language with friends', 'неофициальный', '/ɪnˈfɔːməl/', ARRAY['unit-1']);
SELECT add_word('en', 'I *keep a record of* new words in a notebook', 'вести запись', '/kiːp ə ˈrɛkɔːd ɒv/', ARRAY['unit-1']);
SELECT add_word('en', '*make a note* of the new words', 'сделать заметку, записать', '/meɪk ə nəʊt/', ARRAY['unit-1']);
SELECT add_word('en', 'everyone *makes mistakes* when learning', 'ошибаться, делать ошибки', '/meɪk mɪˈsteɪks/', ARRAY['unit-1']);
SELECT add_word('en', 'how do you *pronounce* this word?', 'произносить', '/prəˈnaʊns/', ARRAY['unit-1']);
SELECT add_word('en', 'her *pronunciation* is almost perfect', 'произношение', '/prəˌnʌnsiˈeɪʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'speech *recognition* has improved a lot', 'узнавание, распознавание', '/ˌrɛkəɡˈnɪʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'I didn''t *recognize* you with glasses', 'узнать', '/ˈrɛkəɡnaɪz/', ARRAY['unit-1']);
SELECT add_word('en', '*record* your voice and listen to it', 'записывать', '/rɪˈkɔːd/', ARRAY['unit-1']);
SELECT add_word('en', 'could you *repeat* that, please?', 'повторять', '/rɪˈpiːt/', ARRAY['unit-1']);
SELECT add_word('en', '*repetition* helps you remember words', 'повторение', '/ˌrɛpɪˈtɪʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'read the *text* and answer the questions', 'текст', '/tɛkst/', ARRAY['unit-1']);
SELECT add_word('en', 'can you *translate* this sentence?', 'переводить', '/trænsˈleɪt/', ARRAY['unit-1']);
SELECT add_word('en', 'the *translation* isn''t quite accurate', 'перевод', '/trænsˈleɪʃən/', ARRAY['unit-1']);
SELECT add_word('en', 'I *work* from home on Fridays', 'работать', '/wɜːk/', ARRAY['unit-1']);
SELECT add_word('en', 'we finally *reached* the top of the hill', 'достигать', '/riːtʃ/', ARRAY['unit-1']);
SELECT add_word('en', 'this job is a great *opportunity*', 'возможность', '/ˌɒpəˈtjuːnɪti/', ARRAY['unit-1']);
SELECT add_word('en', 'they had an *argument* about money', 'спор, ссора', '/ˈɑːɡjʊmənt/', ARRAY['unit-1']);
SELECT add_word('en', 'give me a *chance* to explain', 'возможность, шанс', '/tʃɑːns/', ARRAY['unit-1']);
SELECT add_word('en', 'I need to *revise* for my exam', 'повторять (материал), пересматривать', '/rɪˈvaɪz/', ARRAY['unit-1']);

SELECT add_word('en', 'are you *aware* of the risks?', 'осведомлённый, знающий', '/əˈwɛə/', ARRAY['unit-2']);
SELECT add_word('en', 'thanks for your *encouragement*', 'поддержка, воодушевление', '/ɪnˈkʌrɪdʒmənt/', ARRAY['unit-2']);
SELECT add_word('en', '*after a while*, it got easier', 'спустя некоторое время', '/ˈɑːftər ə waɪl/', ARRAY['unit-2']);
SELECT add_word('en', 'the information is *accurate*', 'точный, безошибочный', '/ˈækjərət/', ARRAY['unit-2']);
SELECT add_word('en', 'try to answer *accurately*', 'точно, безошибочно', '/ˈækjərətli/', ARRAY['unit-2']);
SELECT add_word('en', 'jeans aren''t *appropriate* for the interview', 'подходящий, соответствующий', '/əˈprəʊpriət/', ARRAY['unit-2']);
SELECT add_word('en', 'the door closed with a *bang*', 'удар, грохот, ударять', '/bæŋ/', ARRAY['unit-2']);
SELECT add_word('en', 'is everything *clear*?', 'понятный, ясный', '/klɪə/', ARRAY['unit-2']);
SELECT add_word('en', 'it''s a *complex* problem', 'сложный', '/ˈkɒmplɛks/', ARRAY['unit-2']);
SELECT add_word('en', 'the instructions are too *complicated*', 'сложный, запутанный', '/ˈkɒmplɪkeɪtɪd/', ARRAY['unit-2']);
SELECT add_word('en', 'does this food *contain* sugar?', 'содержать', '/kənˈteɪn/', ARRAY['unit-2']);
SELECT add_word('en', 'describe the plan *in detail*', 'детально, подробно', '/ɪn ˈdiːteɪl/', ARRAY['unit-2']);
SELECT add_word('en', 'learn to use your time *effectively*', 'эффективно', '/ɪˈfɛktɪvli/', ARRAY['unit-2']);
SELECT add_word('en', 'the first results are *encouraging*', 'обнадёживающий, воодушевляющий', '/ɪnˈkʌrɪdʒɪŋ/', ARRAY['unit-2']);
SELECT add_word('en', 'she spoke with great *enthusiasm*', 'энтузиазм', '/ɪnˈθjuːziæzəm/', ARRAY['unit-2']);
SELECT add_word('en', 'he''s very *enthusiastic* about the project', 'полный энтузиазма', '/ɪnˌθjuːziˈæstɪk/', ARRAY['unit-2']);
SELECT add_word('en', 'I want to learn *everyday* English', 'повседневный, бытовой', '/ˈɛvrideɪ/', ARRAY['unit-2']);
SELECT add_word('en', 'I want to *expand* my vocabulary', 'расширять(ся)', '/ɪkˈspænd/', ARRAY['unit-2']);
SELECT add_word('en', 'it''s hard to *express* my feelings in English', 'выражать', '/ɪkˈsprɛs/', ARRAY['unit-2']);
SELECT add_word('en', 'she''s *fluent* in three languages', 'беглый (о языке), свободно говорящий', '/ˈfluːənt/', ARRAY['unit-2']);
SELECT add_word('en', 'he speaks English *fluently*', 'бегло, свободно', '/ˈfluːəntli/', ARRAY['unit-2']);
SELECT add_word('en', 'it''s *frustrating* when nobody understands you', 'раздражающий, разочаровывающий', '/frʌˈstreɪtɪŋ/', ARRAY['unit-2']);
SELECT add_word('en', 'I shouted in *frustration*', 'разочарование, досада', '/frʌˈstreɪʃən/', ARRAY['unit-2']);
SELECT add_word('en', 'your English will *get better* with practice', 'улучшаться', '/ɡɛt ˈbɛtə/', ARRAY['unit-2']);
SELECT add_word('en', 'I want to *improve* my speaking', 'улучшать(ся)', '/ɪmˈpruːv/', ARRAY['unit-2']);
SELECT add_word('en', 'there''s a big *improvement* in your writing', 'улучшение', '/ɪmˈpruːvmənt/', ARRAY['unit-2']);
SELECT add_word('en', 'that joke was *inappropriate*', 'неуместный, неподходящий', '/ˌɪnəˈprəʊpriət/', ARRAY['unit-2']);
SELECT add_word('en', 'does the price *include* breakfast?', 'включать в себя', '/ɪnˈkluːd/', ARRAY['unit-2']);
SELECT add_word('en', 'you''ll *make progress* if you practise every day', 'делать успехи', '/meɪk ˈprəʊɡrɛs/', ARRAY['unit-2']);
SELECT add_word('en', 'she''s very *motivated* to learn', 'мотивированный', '/ˈməʊtɪveɪtɪd/', ARRAY['unit-2']);
SELECT add_word('en', 'I''ve lost my *motivation*', 'мотивация', '/ˌməʊtɪˈveɪʃən/', ARRAY['unit-2']);
SELECT add_word('en', 'the answer is *obvious*', 'очевидный', '/ˈɒbviəs/', ARRAY['unit-2']);
SELECT add_word('en', 'I''m happy with my *progress*', 'прогресс, успехи', '/ˈprəʊɡrɛs/', ARRAY['unit-2']);
SELECT add_word('en', 'the shop sells a *wide range* of books', 'широкий выбор, широкий диапазон', '/waɪd reɪndʒ/', ARRAY['unit-2']);
SELECT add_word('en', 'this is a *specialized* dictionary', 'специализированный', '/ˈspɛʃəlaɪzd/', ARRAY['unit-2']);
SELECT add_word('en', 'it''s an *effective* way to learn', 'эффективный', '/ɪˈfɛktɪv/', ARRAY['unit-2']);
SELECT add_word('en', 'my *aim* is to pass the exam', 'цель', '/eɪm/', ARRAY['unit-2']);
SELECT add_word('en', 'set a *goal* for this month', 'цель', '/ɡəʊl/', ARRAY['unit-2']);
SELECT add_word('en', 'that question is *irrelevant*', 'не относящийся к делу', '/ɪˈrɛləvənt/', ARRAY['unit-2']);
SELECT add_word('en', 'is this information *relevant*?', 'относящийся к делу, актуальный', '/ˈrɛləvənt/', ARRAY['unit-2']);
SELECT add_word('en', 'parents should *encourage* their kids', 'поощрять, воодушевлять', '/ɪnˈkʌrɪdʒ/', ARRAY['unit-2']);

SELECT add_word('en', 'some words, *for example* "gist", are hard to remember', 'например', '/fər ɪɡˈzɑːmpəl/', ARRAY['unit-3']);
SELECT add_word('en', 'how does this *relate* to our topic?', 'относиться, быть связанным', '/rɪˈleɪt/', ARRAY['unit-3']);
SELECT add_word('en', 'these two words are *related*', 'связанный', '/rɪˈleɪtɪd/', ARRAY['unit-3']);
SELECT add_word('en', 'we want to *build* a house', 'строить', '/bɪld/', ARRAY['unit-3']);
SELECT add_word('en', '"make a mistake" is a common *collocation*', 'словосочетание, коллокация', '/ˌkɒləˈkeɪʃən/', ARRAY['unit-3']);
SELECT add_word('en', 'our teacher puts *emphasis* on speaking', 'акцент, особое внимание', '/ˈɛmfəsɪs/', ARRAY['unit-3']);
SELECT add_word('en', 'I want to *emphasize* this point', 'подчёркивать', '/ˈɛmfəsaɪz/', ARRAY['unit-3']);
SELECT add_word('en', 'look up the dictionary *entry*', 'запись, словарная статья', '/ˈɛntri/', ARRAY['unit-3']);
SELECT add_word('en', 'that''s a common *expression*', 'выражение', '/ɪkˈsprɛʃən/', ARRAY['unit-3']);
SELECT add_word('en', 'some cities, *for instance* London, are expensive', 'например', '/fər ˈɪnstəns/', ARRAY['unit-3']);
SELECT add_word('en', 'I didn''t mean to *offend* you', 'обижать', '/əˈfɛnd/', ARRAY['unit-3']);
SELECT add_word('en', 'that word is *offensive*', 'оскорбительный', '/əˈfɛnsɪv/', ARRAY['unit-3']);
SELECT add_word('en', 'the school will *provide* the books', 'предоставлять', '/prəˈvaɪd/', ARRAY['unit-3']);
SELECT add_word('en', '*select* the correct answer', 'выбирать', '/sɪˈlɛkt/', ARRAY['unit-3']);
SELECT add_word('en', 'the shop has a good *selection* of teas', 'выбор, отбор', '/sɪˈlɛkʃən/', ARRAY['unit-3']);
SELECT add_word('en', '"cool" is a *slang* word', 'сленг', '/slæŋ/', ARRAY['unit-3']);
SELECT add_word('en', 'where''s the *stress* in this word?', 'ударение', '/strɛs/', ARRAY['unit-3']);
SELECT add_word('en', 'the stress is on the first *syllable*', 'слог', '/ˈsɪləbəl/', ARRAY['unit-3']);
SELECT add_word('en', 'the dove is a *symbol* of peace', 'символ', '/ˈsɪmbəl/', ARRAY['unit-3']);
SELECT add_word('en', 'how would you *define* this word?', 'давать определение', '/dɪˈfaɪn/', ARRAY['unit-3']);
SELECT add_word('en', '"break the ice" is an *idiom*', 'идиома', '/ˈɪdiəm/', ARRAY['unit-3']);
SELECT add_word('en', '*choose* one of the options', 'выбирать', '/tʃuːz/', ARRAY['unit-3']);
SELECT add_word('en', 'try to *avoid* this mistake', 'избегать', '/əˈvɔɪd/', ARRAY['unit-3']);
SELECT add_word('en', 'read the *definition* in the dictionary', 'определение', '/ˌdɛfɪˈnɪʃən/', ARRAY['unit-3']);
SELECT add_word('en', 'I like your writing *style*', 'стиль', '/staɪl/', ARRAY['unit-3']);

SELECT add_word('en', 'put a *mark* next to the correct answer', 'знак, отметка', '/mɑːk/', ARRAY['unit-4']);
SELECT add_word('en', '"etc." is an *abbreviation*', 'сокращение, аббревиатура', '/əˌbriːviˈeɪʃən/', ARRAY['unit-4']);
SELECT add_word('en', 'is there an *alternative* route?', 'альтернативный, другой', '/ɔːlˈtɜːnətɪv/', ARRAY['unit-4']);
SELECT add_word('en', 'don''t forget the *apostrophe* in "don''t"', 'апостроф', '/əˈpɒstrəfi/', ARRAY['unit-4']);
SELECT add_word('en', 'write the answer in *brackets*', 'скобки', '/ˈbrækɪts/', ARRAY['unit-4']);
SELECT add_word('en', 'start a sentence with a *capital letter*', 'заглавная буква', '/ˈkæpɪtəl ˈlɛtə/', ARRAY['unit-4']);
SELECT add_word('en', 'use a *colon* before a list', 'двоеточие', '/ˈkəʊlən/', ARRAY['unit-4']);
SELECT add_word('en', 'put a *comma* after "however"', 'запятая', '/ˈkɒmə/', ARRAY['unit-4']);
SELECT add_word('en', '*connect* the two sentences', 'соединять', '/kəˈnɛkt/', ARRAY['unit-4']);
SELECT add_word('en', 'use a *dash* to show a pause', 'тире', '/dæʃ/', ARRAY['unit-4']);
SELECT add_word('en', 'the storm could *destroy* the crops', 'уничтожать', '/dɪˈstrɔɪ/', ARRAY['unit-4']);
SELECT add_word('en', '*divide* the text into paragraphs', 'делить', '/dɪˈvaɪd/', ARRAY['unit-4']);
SELECT add_word('en', 'end the sentence with an *exclamation mark*', 'восклицательный знак', '/ˌɛkskləˈmeɪʃən mɑːk/', ARRAY['unit-4']);
SELECT add_word('en', 'every sentence ends with a *full stop*', 'точка', '/fʊl stɒp/', ARRAY['unit-4']);
SELECT add_word('en', '"well-known" has a *hyphen*', 'дефис', '/ˈhaɪfən/', ARRAY['unit-4']);
SELECT add_word('en', '*join* the two parts together', 'соединять', '/dʒɔɪn/', ARRAY['unit-4']);
SELECT add_word('en', 'make a *list* of new words', 'список', '/lɪst/', ARRAY['unit-4']);
SELECT add_word('en', '*pause* before the important word', 'пауза, делать паузу', '/pɔːz/', ARRAY['unit-4']);
SELECT add_word('en', 'a question ends with a *question mark*', 'вопросительный знак', '/ˈkwɛstʃən mɑːk/', ARRAY['unit-4']);
SELECT add_word('en', 'put the title in *quotation marks*', 'кавычки', '/kwəʊˈteɪʃən mɑːks/', ARRAY['unit-4']);
SELECT add_word('en', 'a *semicolon* can join two sentences', 'точка с запятой', '/ˌsɛmiˈkəʊlən/', ARRAY['unit-4']);
SELECT add_word('en', '*separate* the words with commas', 'разделять', '/ˈsɛpəreɪt/', ARRAY['unit-4']);
SELECT add_word('en', 'don''t forget the *shopping list*', 'список покупок', '/ˈʃɒpɪŋ lɪst/', ARRAY['unit-4']);
SELECT add_word('en', 'write "and/or" with a *slash*', 'косая черта, слэш', '/slæʃ/', ARRAY['unit-4']);
SELECT add_word('en', 'write your name in *small letters*', 'строчные буквы', '/smɔːl ˈlɛtəz/', ARRAY['unit-4']);
SELECT add_word('en', 'I like fruit *such as* apples and pears', 'такие как', '/sʌtʃ æz/', ARRAY['unit-4']);
SELECT add_word('en', 'he''s a *loyal* friend', 'верный, преданный', '/ˈlɔɪəl/', ARRAY['unit-4']);
SELECT add_word('en', 'I love cities *like* Paris and Rome', 'такие как, как', '/laɪk/', ARRAY['unit-4']);
SELECT add_word('en', 'sorry to *interrupt* you', 'прерывать, перебивать', '/ˌɪntəˈrʌpt/', ARRAY['unit-4']);
SELECT add_word('en', 'let''s have tea *instead*', 'вместо (этого)', '/ɪnˈstɛd/', ARRAY['unit-4']);
SELECT add_word('en', 'you can *leave out* this word', 'пропустить, не включать', '/liːv aʊt/', ARRAY['unit-4']);
SELECT add_word('en', 'you can *omit* the article here', 'опустить, пропустить', '/əˈmɪt/', ARRAY['unit-4']);
SELECT add_word('en', 'I read the news *daily*', 'ежедневно, ежедневный', '/ˈdeɪli/', ARRAY['unit-4']);

-- +goose Down
