-- +goose Up
-- Units 5-10 should not be in the "self" group: unlink them (words, units and
-- progress stay).
DELETE FROM word_groups wg
USING groups self
WHERE self.name = 'self'
  AND wg.group_id = self.id
  AND EXISTS (
      SELECT 1 FROM word_groups u
      JOIN groups ug ON ug.id = u.group_id
      WHERE u.word_id = wg.word_id
        AND ug.name IN ('unit-5', 'unit-6', 'unit-7', 'unit-8', 'unit-9', 'unit-10')
  );

-- An earlier draft of 00005 stored only the starred part as the translation and the
-- full explanation as the note. Bring such cards to the final format: the full
-- explanation with *asterisks* and no note. Cards already in that format have no note
-- and are left alone.
UPDATE words w
SET translation = v.translation, note = NULL
FROM (VALUES
    ('he is *clean-shaven*', 'he has *no beard or moustache*'),
    ('the music is too *loud*', 'the music is *making too much noise*'),
    ('her *appearance* changed a lot', 'the way she *looks* changed a lot'),
    ('my dad is going *bald*', 'my dad is *losing the hair on his head*'),
    ('he has *broad shoulders*', 'he has *wide shoulders*'),
    ('I wear *contact lenses*', 'I wear *small lenses on my eyes instead of glasses*'),
    ('she is *dark-skinned*', 'she has *dark skin*'),
    ('she is *expecting a baby*', 'she is *pregnant*'),
    ('he raised his *eyebrows*', 'he raised *the lines of hair above his eyes*'),
    ('he''s a bit *fattish*', 'he''s *a little fat*'),
    ('he started to *go bald*', 'he started to *lose his hair*'),
    ('he started to *go grey* at 40', 'his hair started to *turn grey* at 40'),
    ('my grandpa *went white*', 'my grandpa''s *hair became completely white*'),
    ('many men *lose their hair*', 'many men *become bald*'),
    ('I''m *in bad shape*', 'I''m *not fit*'),
    ('she''s *in good shape*', 'she''s *fit and healthy*'),
    ('he is *light-skinned*', 'he has *light skin*'),
    ('her room is always *neat*', 'her room is always *tidy and organised*'),
    ('she is *pale-skinned*', 'she has *very light skin*'),
    ('the baby is *plump*', 'the baby is *a little round and fat in a nice way*'),
    ('she is *pregnant*', 'she is *expecting a baby*'),
    ('she has a *pretty* face', 'she has an *attractive* face'),
    ('he has a *receding* hairline', 'his hair is *disappearing from the front*'),
    ('the wall feels *rough*', 'the wall feels *uneven, not smooth*'),
    ('he has a *roundish* face', 'he has a *fairly round* face'),
    ('he has a *scar* on his cheek', 'he has *a mark from an old wound* on his cheek'),
    ('what *sex* is the baby?', 'is the baby *a boy or a girl*?'),
    ('the model is very *skinny*', 'the model is *very thin*'),
    ('she has *slender* fingers', 'she has *long and thin* fingers in an elegant way'),
    ('he is tall and *slim*', 'he is tall and *thin in an attractive way*'),
    ('the baby''s skin is *smooth*', 'the baby''s skin is *soft and even*'),
    ('he is short and *stocky*', 'he is short and *broad and strong*'),
    ('he has *stubble* on his chin', 'he has *short hair growing* on his chin'),
    ('he''s *tallish*', 'he''s *fairly tall*'),
    ('she came back with a *tan*', 'she came back with *darker skin from the sun*'),
    ('she came back *tanned*', 'she came back *with darker skin from the sun*'),
    ('I can''t *tell* them apart', 'I can''t *see the difference* between them'),
    ('he is *well built*', 'he has *a strong, muscular body*'),
    ('my grandma has *wrinkles*', 'my grandma has *lines on her face from age*'),
    ('he looks *youngish*', 'he looks *fairly young*'),
    ('the *female* lion hunts', 'the *girl* lion hunts'),
    ('the *male* bird is colourful', 'the *boy* bird is colourful'),
    ('she has a great *figure*', 'she has a great *body shape*'),
    ('the lecture was *dull*', 'the lecture was *boring*'),
    ('you must be *mad*', 'you must be *crazy*'),
    ('*aggression* is never the answer', '*violent, angry behaviour* is never the answer'),
    ('the dog is *aggressive*', 'the dog *wants to attack*'),
    ('her *ambition* is to be a doctor', 'her *big goal* is to be a doctor'),
    ('he is very *ambitious*', 'he *really wants to succeed*'),
    ('his *arrogance* annoys me', 'his *feeling that he''s better than others* annoys me'),
    ('she is so *arrogant*', 'she *thinks she''s better than everyone*'),
    ('he is always *cheerful*', 'he is always *happy and positive*'),
    ('that''s a *crazy* idea', 'that''s a *mad, strange* idea'),
    ('he is *dishonest*', 'he *lies and can''t be trusted*'),
    ('she is *easy-going*', 'she is *relaxed and not easily upset*'),
    ('the kids are so *energetic*', 'the kids are so *active and full of energy*'),
    ('I have no *energy* today', 'I have no *strength to do things* today'),
    ('thank you for your *generosity*', 'thank you for *being so kind and giving*'),
    ('he is very *generous*', 'he *likes giving money and help to others*'),
    ('she is *hard-working*', 'she *works a lot and puts in effort*'),
    ('please be *honest* with me', 'please *tell me the truth*'),
    ('*honesty* is important', '*telling the truth* is important'),
    ('he has a great *sense of humour*', 'he is *really funny and gets jokes*'),
    ('don''t be so *impatient*', 'don''t be so *unable to wait calmly*'),
    ('he is *intolerant* of other opinions', 'he *doesn''t accept* other opinions'),
    ('it was *irresponsible* of you', 'it was *careless and wrong* of you'),
    ('he is too *lazy* to cook', 'he *doesn''t want to make the effort* to cook'),
    ('don''t be *mean* to your sister', 'don''t be *unkind* to your sister'),
    ('she is *modest* about her success', 'she *doesn''t boast* about her success'),
    ('*patience* is a virtue', '*the ability to wait calmly* is a virtue'),
    ('the *patient* is waiting for the doctor', 'the *sick person* is waiting for the doctor'),
    ('she is very *responsible*', 'she *can be trusted to do the right thing*'),
    ('she is *self-confident*', 'she *believes in herself*'),
    ('it was a *stupid* mistake', 'it was a *silly, foolish* mistake'),
    ('we need more *tolerance*', 'we need more *acceptance of differences*'),
    ('my parents are very *tolerant*', 'my parents *accept other people''s views*'),
    ('he is completely *unambitious*', 'he *has no desire to succeed*'),
    ('she feels *insecure* about her looks', 'she *isn''t confident* about her looks'),
    ('I''m *absolutely* sure', 'I''m *completely* sure'),
    ('I''m *anxious* about the exam', 'I''m *worried and nervous* about the exam'),
    ('I was *delighted* with the gift', 'I was *very happy* with the gift'),
    ('he never shows his *emotions*', 'he never shows his *feelings*'),
    ('she gets very *emotional*', 'she *shows her feelings strongly*'),
    ('I''m *envious* of his success', 'I *wish I had* his success'),
    ('I''m *fed up* with this job', 'I''m *tired and annoyed* with this job'),
    ('she was *furious*', 'she was *extremely angry*'),
    ('he was *heartbroken* after the breakup', 'he was *extremely sad* after the breakup'),
    ('he always *hides his feelings*', 'he never *shows what he feels*'),
    ('you *hurt her feelings*', 'you *made her feel upset*'),
    ('he''s *in a bad mood* today', 'he''s *grumpy and irritated* today'),
    ('she''s *in a good mood*', 'she''s *happy and cheerful*'),
    ('that was *insensitive*', 'that was *careless about other people''s feelings*'),
    ('he is *jealous* of his brother', 'he *is upset that his brother has something he wants*'),
    ('I feel *miserable*', 'I feel *very unhappy*'),
    ('my *mood* changes fast', '*the way I feel* changes fast'),
    ('she is so *moody*', 'her *feelings change quickly*'),
    ('I''m *proud* of you', 'I''m *pleased with what you did*'),
    ('I was *scared stiff*', 'I was *so scared I couldn''t move*'),
    ('he is very *sensitive*', 'he *gets hurt easily*'),
    ('it''s ok to *show your feelings*', 'it''s ok to *let people see what you feel*'),
    ('my friends are very *supportive*', 'my friends *always help and encourage me*'),
    ('she was *sympathetic*', 'she *understood and cared about my problem*'),
    ('I was *thrilled* with the news', 'I was *very excited* with the news'),
    ('I''m *very* tired', 'I''m *extremely* tired'),
    ('I''m *terrified* of spiders', 'I''m *extremely afraid* of spiders'),
    ('I was *amazed* by the view', 'I was *very surprised and impressed* by the view'),
    ('I was *astonished*', 'I was *extremely surprised*'),
    ('*in general*, I like my job', '*overall*, I like my job'),
    ('that was *cruel*', 'that was *intentionally hurtful*'),
    ('he is a bit *antisocial*', 'he *avoids being around people*'),
    ('we always *argue* about money', 'we always *disagree angrily* about money'),
    ('she is my *close friend*', 'she is *a friend I''m very connected to*'),
    ('I *fell out with* my brother', 'I *stopped being friends* with my brother after an argument'),
    ('it''s easy to *make friends* here', 'it''s easy to *start friendships* here'),
    ('the people here are *friendly*', 'the people here are *kind and welcoming*'),
    ('our *friendship* is strong', 'our *relationship as friends* is strong'),
    ('I want to *get to know* you', 'I want to *learn more about* you'),
    ('he *goes out with* my sister', 'he *is dating* my sister'),
    ('we *have a lot in common*', 'we *share many interests*'),
    ('they *had a row* last night', 'they *had a loud argument* last night'),
    ('we *have nothing in common*', 'we *share no interests at all*'),
    ('she is *in a relationship*', 'she *has a partner*'),
    ('let''s *keep in touch*', 'let''s *stay in contact*'),
    ('he''s an *old friend*', 'he''s a friend *I''ve known for many years*'),
    ('I didn''t *realize* it was late', 'I didn''t *notice* it was late'),
    ('he is very *reliable*', 'he *can always be trusted*'),
    ('they *split up* last year', 'they *ended their relationship* last year'),
    ('I *trust* you', 'I *believe you are honest*'),
    ('he was *disloyal* to his team', 'he *betrayed* his team'),
    ('I *regret* saying that', 'I *wish I hadn''t said* that'),
    ('you can *rely on* me', 'you can *depend on* me'),
    ('let''s *get together* this weekend', 'let''s *meet up* this weekend'),
    ('it *depends* on the weather', 'it *is decided by* the weather'),
    ('everything *went wrong*', 'everything *failed*'),
    ('he is my *stepbrother*', 'he is *my stepparent''s son*'),
    ('they want to *adopt* a child', 'they want to *legally take a child as their own*'),
    ('my *ancestors* came from Italy', 'my *family members from long ago* came from Italy'),
    ('my grandma *brought me up*', 'my grandma *raised me*'),
    ('they *emigrated* to Canada', 'they *left their country to live* in Canada'),
    ('she became a *foster parent*', 'she *takes care of other people''s children for a time*'),
    ('the older *generation*', 'the older *group of people born around the same time*'),
    ('they *got divorced*', 'they *legally ended their marriage*'),
    ('he is my *half-brother*', 'he is *my brother through one parent*'),
    ('she is my *half-sister*', 'she is *my sister through one parent*'),
    ('the *king* gave a speech', 'the *male ruler of the country* gave a speech'),
    ('you *look like* your mum', 'you *have the same appearance as* your mum'),
    ('I''m an *only child*', 'I *have no brothers or sisters*'),
    ('*originally*, I''m from Serbia', '*at first*, I''m from Serbia'),
    ('my *previous* job was boring', 'my *last* job was boring'),
    ('the *queen* visited the city', 'the *female ruler* visited the city'),
    ('are you two *related*?', 'are you two *in the same family*?'),
    ('all my *relatives* came', 'all my *family members* came'),
    ('the *royal* family', 'the *king and queen''s* family'),
    ('she is a *single parent*', 'she *raises her child alone*'),
    ('she is his *stepdaughter*', 'she is *his wife''s daughter*'),
    ('he is my *stepfather*', 'he is *my mother''s husband*, not my real dad'),
    ('she is my *stepmother*', 'she is *my father''s wife*, not my real mum'),
    ('she is my *stepsister*', 'she is *my stepparent''s daughter*'),
    ('he is her *stepson*', 'he is *her husband''s son*'),
    ('my parents *support* me', 'my parents *help* me'),
    ('he is an *immigrant*', 'he is *a person who came to live in another country*'),
    ('she *takes after* her father', 'she *has the same character as* her father'),
    ('today is our *anniversary*', 'today is *the day we got married years ago*'),
    ('he was the *best man*', 'he was *the groom''s main helper at the wedding*'),
    ('the *bride* looked beautiful', 'the *woman getting married* looked beautiful'),
    ('she was a *bridesmaid*', 'she was *the bride''s helper at the wedding*'),
    ('the *burial* was private', '*putting the body in the ground* was private'),
    ('they *buried* him yesterday', 'they *put his body in the ground* yesterday'),
    ('let''s *celebrate*', 'let''s *have fun because of a special event*'),
    ('he is buried in the *cemetery*', 'he is buried in the *place where dead people lie*'),
    ('the *ceremony* was beautiful', 'the *formal event* was beautiful'),
    ('they had a *civil ceremony*', 'they *got married officially, not in a church*'),
    ('the *coffin* was made of oak', 'the *box for the dead body* was made of oak'),
    ('they''re a lovely *couple*', 'they''re a lovely *pair in a relationship*'),
    ('he wanted to be *cremated*', 'he wanted *his body to be burned after death*'),
    ('*cremation* is common here', '*burning the body after death* is common here'),
    ('the plant is *dead*', 'the plant is *no longer alive*'),
    ('his *death* was sudden', '*the end of his life* was sudden'),
    ('he *died* last year', 'he *stopped living* last year'),
    ('let''s *drink a toast* to them', 'let''s *raise our glasses and drink* to them'),
    ('the *funeral* is on Monday', 'the *ceremony for the dead person* is on Monday'),
    ('we visited his *grave*', 'we visited *the place where he is buried*'),
    ('the *gravestone* had his name', 'the *stone on the grave* had his name'),
    ('the *groom* was nervous', 'the *man getting married* was nervous'),
    ('we have twenty *guests*', 'we have twenty *invited people*'),
    ('they went to Bali for their *honeymoon*', 'they went to Bali for *their holiday after the wedding*'),
    ('he is my *husband*', 'he is *the man I''m married to*'),
    ('the family is *in mourning*', 'the family is *grieving after a death*'),
    ('she will *inherit* the house', 'she will *get the house after someone''s death*'),
    ('he spent his *inheritance*', 'he spent *the money he got from a dead relative*'),
    ('he *made a speech* at the wedding', 'he *spoke formally in front of everyone* at the wedding'),
    ('their *marriage* lasted 50 years', 'their *life as husband and wife* lasted 50 years'),
    ('the *mourners* wore black', 'the *people grieving at the funeral* wore black'),
    ('a period of *mourning*', 'a period of *sadness after a death*'),
    ('the *reception* was in a hotel', 'the *formal party* was in a hotel'),
    ('she is very *religious*', 'she *strongly believes in God*'),
    ('they had a *religious ceremony*', 'they *got married in a church*'),
    ('it''s a *traditional* dish', 'it''s a dish *made the old, usual way*'),
    ('their *wedding* is in June', 'their *marriage ceremony* is in June'),
    ('the *wedding reception* was fun', 'the *party after the wedding* was fun'),
    ('she is a *widow*', 'she is *a woman whose husband died*'),
    ('he is a *widower*', 'he is *a man whose wife died*'),
    ('she is my *wife*', 'she is *the woman I''m married to*'),
    ('he left everything in his *will*', 'he left everything in *the document about his property after death*'),
    ('make a *wish*', '*say what you want to happen*'),
    ('it''s your *choice*', 'it''s your *decision*')
) AS v (word, translation)
WHERE w.language = 'en' AND w.word = v.word AND w.note IS NOT NULL;

-- +goose Down
