-- +goose Up
-- Units 5-10. *Asterisks* mark the word being learned and the part of the
-- explanation that matches it; typing just that part counts as a correct answer.

SELECT add_word('en', 'he is *clean-shaven*', 'he has *no beard or moustache*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the music is too *loud*', 'the music is *making too much noise*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'her *appearance* changed a lot', 'the way she *looks* changed a lot', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'my dad is going *bald*', 'my dad is *losing the hair on his head*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he has *broad shoulders*', 'he has *wide shoulders*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'I wear *contact lenses*', 'I wear *small lenses on my eyes instead of glasses*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she is *dark-skinned*', 'she has *dark skin*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she is *expecting a baby*', 'she is *pregnant*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he raised his *eyebrows*', 'he raised *the lines of hair above his eyes*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he''s a bit *fattish*', 'he''s *a little fat*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he started to *go bald*', 'he started to *lose his hair*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he started to *go grey* at 40', 'his hair started to *turn grey* at 40', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'my grandpa *went white*', 'my grandpa''s *hair became completely white*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'many men *lose their hair*', 'many men *become bald*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'I''m *in bad shape*', 'I''m *not fit*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she''s *in good shape*', 'she''s *fit and healthy*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he is *light-skinned*', 'he has *light skin*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'her room is always *neat*', 'her room is always *tidy and organised*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she is *pale-skinned*', 'she has *very light skin*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the baby is *plump*', 'the baby is *a little round and fat in a nice way*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she is *pregnant*', 'she is *expecting a baby*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she has a *pretty* face', 'she has an *attractive* face', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he has a *receding* hairline', 'his hair is *disappearing from the front*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the wall feels *rough*', 'the wall feels *uneven, not smooth*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he has a *roundish* face', 'he has a *fairly round* face', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he has a *scar* on his cheek', 'he has *a mark from an old wound* on his cheek', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'what *sex* is the baby?', 'is the baby *a boy or a girl*?', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the model is very *skinny*', 'the model is *very thin*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she has *slender* fingers', 'she has *long and thin* fingers in an elegant way', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he is tall and *slim*', 'he is tall and *thin in an attractive way*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the baby''s skin is *smooth*', 'the baby''s skin is *soft and even*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he is short and *stocky*', 'he is short and *broad and strong*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he has *stubble* on his chin', 'he has *short hair growing* on his chin', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he''s *tallish*', 'he''s *fairly tall*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she came back with a *tan*', 'she came back with *darker skin from the sun*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she came back *tanned*', 'she came back *with darker skin from the sun*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'I can''t *tell* them apart', 'I can''t *see the difference* between them', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he is *well built*', 'he has *a strong, muscular body*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'my grandma has *wrinkles*', 'my grandma has *lines on her face from age*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'he looks *youngish*', 'he looks *fairly young*', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the *female* lion hunts', 'the *girl* lion hunts', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'the *male* bird is colourful', 'the *boy* bird is colourful', NULL, ARRAY['self', 'unit-5']);
SELECT add_word('en', 'she has a great *figure*', 'she has a great *body shape*', NULL, ARRAY['self', 'unit-5']);

SELECT add_word('en', 'the lecture was *dull*', 'the lecture was *boring*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'you must be *mad*', 'you must be *crazy*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', '*aggression* is never the answer', '*violent, angry behaviour* is never the answer', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'the dog is *aggressive*', 'the dog *wants to attack*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'her *ambition* is to be a doctor', 'her *big goal* is to be a doctor', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is very *ambitious*', 'he *really wants to succeed*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'his *arrogance* annoys me', 'his *feeling that he''s better than others* annoys me', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she is so *arrogant*', 'she *thinks she''s better than everyone*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is always *cheerful*', 'he is always *happy and positive*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'that''s a *crazy* idea', 'that''s a *mad, strange* idea', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is *dishonest*', 'he *lies and can''t be trusted*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she is *easy-going*', 'she is *relaxed and not easily upset*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'the kids are so *energetic*', 'the kids are so *active and full of energy*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'I have no *energy* today', 'I have no *strength to do things* today', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'thank you for your *generosity*', 'thank you for *being so kind and giving*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is very *generous*', 'he *likes giving money and help to others*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she is *hard-working*', 'she *works a lot and puts in effort*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'please be *honest* with me', 'please *tell me the truth*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', '*honesty* is important', '*telling the truth* is important', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he has a great *sense of humour*', 'he is *really funny and gets jokes*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'don''t be so *impatient*', 'don''t be so *unable to wait calmly*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is *intolerant* of other opinions', 'he *doesn''t accept* other opinions', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'it was *irresponsible* of you', 'it was *careless and wrong* of you', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is too *lazy* to cook', 'he *doesn''t want to make the effort* to cook', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'don''t be *mean* to your sister', 'don''t be *unkind* to your sister', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she is *modest* about her success', 'she *doesn''t boast* about her success', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', '*patience* is a virtue', '*the ability to wait calmly* is a virtue', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'the *patient* is waiting for the doctor', 'the *sick person* is waiting for the doctor', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she is very *responsible*', 'she *can be trusted to do the right thing*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she is *self-confident*', 'she *believes in herself*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'it was a *stupid* mistake', 'it was a *silly, foolish* mistake', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'we need more *tolerance*', 'we need more *acceptance of differences*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'my parents are very *tolerant*', 'my parents *accept other people''s views*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'he is completely *unambitious*', 'he *has no desire to succeed*', NULL, ARRAY['self', 'unit-6']);
SELECT add_word('en', 'she feels *insecure* about her looks', 'she *isn''t confident* about her looks', NULL, ARRAY['self', 'unit-6']);

SELECT add_word('en', 'I''m *absolutely* sure', 'I''m *completely* sure', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I''m *anxious* about the exam', 'I''m *worried and nervous* about the exam', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I was *delighted* with the gift', 'I was *very happy* with the gift', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'he never shows his *emotions*', 'he never shows his *feelings*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'she gets very *emotional*', 'she *shows her feelings strongly*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I''m *envious* of his success', 'I *wish I had* his success', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I''m *fed up* with this job', 'I''m *tired and annoyed* with this job', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'she was *furious*', 'she was *extremely angry*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'he was *heartbroken* after the breakup', 'he was *extremely sad* after the breakup', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'he always *hides his feelings*', 'he never *shows what he feels*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'you *hurt her feelings*', 'you *made her feel upset*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'he''s *in a bad mood* today', 'he''s *grumpy and irritated* today', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'she''s *in a good mood*', 'she''s *happy and cheerful*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'that was *insensitive*', 'that was *careless about other people''s feelings*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'he is *jealous* of his brother', 'he *is upset that his brother has something he wants*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I feel *miserable*', 'I feel *very unhappy*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'my *mood* changes fast', '*the way I feel* changes fast', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'she is so *moody*', 'her *feelings change quickly*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I''m *proud* of you', 'I''m *pleased with what you did*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I was *scared stiff*', 'I was *so scared I couldn''t move*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'he is very *sensitive*', 'he *gets hurt easily*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'it''s ok to *show your feelings*', 'it''s ok to *let people see what you feel*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'my friends are very *supportive*', 'my friends *always help and encourage me*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'she was *sympathetic*', 'she *understood and cared about my problem*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I was *thrilled* with the news', 'I was *very excited* with the news', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I''m *very* tired', 'I''m *extremely* tired', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I''m *terrified* of spiders', 'I''m *extremely afraid* of spiders', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I was *amazed* by the view', 'I was *very surprised and impressed* by the view', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'I was *astonished*', 'I was *extremely surprised*', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', '*in general*, I like my job', '*overall*, I like my job', NULL, ARRAY['self', 'unit-7']);
SELECT add_word('en', 'that was *cruel*', 'that was *intentionally hurtful*', NULL, ARRAY['self', 'unit-7']);

SELECT add_word('en', 'he is a bit *antisocial*', 'he *avoids being around people*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'we always *argue* about money', 'we always *disagree angrily* about money', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'she is my *close friend*', 'she is *a friend I''m very connected to*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'I *fell out with* my brother', 'I *stopped being friends* with my brother after an argument', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'it''s easy to *make friends* here', 'it''s easy to *start friendships* here', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'the people here are *friendly*', 'the people here are *kind and welcoming*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'our *friendship* is strong', 'our *relationship as friends* is strong', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'I want to *get to know* you', 'I want to *learn more about* you', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'he *goes out with* my sister', 'he *is dating* my sister', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'we *have a lot in common*', 'we *share many interests*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'they *had a row* last night', 'they *had a loud argument* last night', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'we *have nothing in common*', 'we *share no interests at all*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'she is *in a relationship*', 'she *has a partner*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'let''s *keep in touch*', 'let''s *stay in contact*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'he''s an *old friend*', 'he''s a friend *I''ve known for many years*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'I didn''t *realize* it was late', 'I didn''t *notice* it was late', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'he is very *reliable*', 'he *can always be trusted*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'they *split up* last year', 'they *ended their relationship* last year', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'I *trust* you', 'I *believe you are honest*', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'he was *disloyal* to his team', 'he *betrayed* his team', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'I *regret* saying that', 'I *wish I hadn''t said* that', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'you can *rely on* me', 'you can *depend on* me', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'let''s *get together* this weekend', 'let''s *meet up* this weekend', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'it *depends* on the weather', 'it *is decided by* the weather', NULL, ARRAY['self', 'unit-8']);
SELECT add_word('en', 'everything *went wrong*', 'everything *failed*', NULL, ARRAY['self', 'unit-8']);

SELECT add_word('en', 'he is my *stepbrother*', 'he is *my stepparent''s son*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'they want to *adopt* a child', 'they want to *legally take a child as their own*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'my *ancestors* came from Italy', 'my *family members from long ago* came from Italy', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'my grandma *brought me up*', 'my grandma *raised me*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'they *emigrated* to Canada', 'they *left their country to live* in Canada', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she became a *foster parent*', 'she *takes care of other people''s children for a time*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'the older *generation*', 'the older *group of people born around the same time*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'they *got divorced*', 'they *legally ended their marriage*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'he is my *half-brother*', 'he is *my brother through one parent*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she is my *half-sister*', 'she is *my sister through one parent*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'the *king* gave a speech', 'the *male ruler of the country* gave a speech', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'you *look like* your mum', 'you *have the same appearance as* your mum', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'I''m an *only child*', 'I *have no brothers or sisters*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', '*originally*, I''m from Serbia', '*at first*, I''m from Serbia', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'my *previous* job was boring', 'my *last* job was boring', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'the *queen* visited the city', 'the *female ruler* visited the city', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'are you two *related*?', 'are you two *in the same family*?', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'all my *relatives* came', 'all my *family members* came', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'the *royal* family', 'the *king and queen''s* family', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she is a *single parent*', 'she *raises her child alone*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she is his *stepdaughter*', 'she is *his wife''s daughter*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'he is my *stepfather*', 'he is *my mother''s husband*, not my real dad', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she is my *stepmother*', 'she is *my father''s wife*, not my real mum', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she is my *stepsister*', 'she is *my stepparent''s daughter*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'he is her *stepson*', 'he is *her husband''s son*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'my parents *support* me', 'my parents *help* me', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'he is an *immigrant*', 'he is *a person who came to live in another country*', NULL, ARRAY['self', 'unit-9']);
SELECT add_word('en', 'she *takes after* her father', 'she *has the same character as* her father', NULL, ARRAY['self', 'unit-9']);

SELECT add_word('en', 'today is our *anniversary*', 'today is *the day we got married years ago*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he was the *best man*', 'he was *the groom''s main helper at the wedding*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *bride* looked beautiful', 'the *woman getting married* looked beautiful', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'she was a *bridesmaid*', 'she was *the bride''s helper at the wedding*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *burial* was private', '*putting the body in the ground* was private', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'they *buried* him yesterday', 'they *put his body in the ground* yesterday', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'let''s *celebrate*', 'let''s *have fun because of a special event*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he is buried in the *cemetery*', 'he is buried in the *place where dead people lie*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *ceremony* was beautiful', 'the *formal event* was beautiful', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'they had a *civil ceremony*', 'they *got married officially, not in a church*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *coffin* was made of oak', 'the *box for the dead body* was made of oak', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'they''re a lovely *couple*', 'they''re a lovely *pair in a relationship*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he wanted to be *cremated*', 'he wanted *his body to be burned after death*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', '*cremation* is common here', '*burning the body after death* is common here', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the plant is *dead*', 'the plant is *no longer alive*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'his *death* was sudden', '*the end of his life* was sudden', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he *died* last year', 'he *stopped living* last year', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'let''s *drink a toast* to them', 'let''s *raise our glasses and drink* to them', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *funeral* is on Monday', 'the *ceremony for the dead person* is on Monday', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'we visited his *grave*', 'we visited *the place where he is buried*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *gravestone* had his name', 'the *stone on the grave* had his name', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *groom* was nervous', 'the *man getting married* was nervous', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'we have twenty *guests*', 'we have twenty *invited people*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'they went to Bali for their *honeymoon*', 'they went to Bali for *their holiday after the wedding*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he is my *husband*', 'he is *the man I''m married to*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the family is *in mourning*', 'the family is *grieving after a death*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'she will *inherit* the house', 'she will *get the house after someone''s death*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he spent his *inheritance*', 'he spent *the money he got from a dead relative*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he *made a speech* at the wedding', 'he *spoke formally in front of everyone* at the wedding', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'their *marriage* lasted 50 years', 'their *life as husband and wife* lasted 50 years', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *mourners* wore black', 'the *people grieving at the funeral* wore black', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'a period of *mourning*', 'a period of *sadness after a death*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *reception* was in a hotel', 'the *formal party* was in a hotel', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'she is very *religious*', 'she *strongly believes in God*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'they had a *religious ceremony*', 'they *got married in a church*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'it''s a *traditional* dish', 'it''s a dish *made the old, usual way*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'their *wedding* is in June', 'their *marriage ceremony* is in June', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'the *wedding reception* was fun', 'the *party after the wedding* was fun', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'she is a *widow*', 'she is *a woman whose husband died*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he is a *widower*', 'he is *a man whose wife died*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'she is my *wife*', 'she is *the woman I''m married to*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'he left everything in his *will*', 'he left everything in *the document about his property after death*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'make a *wish*', '*say what you want to happen*', NULL, ARRAY['self', 'unit-10']);
SELECT add_word('en', 'it''s your *choice*', 'it''s your *decision*', NULL, ARRAY['self', 'unit-10']);

-- +goose Down
